CLASS zrap110_travel_event_handl_001 DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF zrap110_r_traveltp_001
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZRAP110_TRAVEL_EVENT_HANDL_001 IMPLEMENTATION.
ENDCLASS.
